[package]
name = "filehost-spc"
version = "0.1.0"
edition = "2021"
authors = ["Lut99"]

[dependencies]
log = { version = "0.4.16", features = ["std", "serde"] }
serde = "1.0.136"
serde_json = "1.0.79"
